services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: weather_backend
    ports:
      - ${BACKEND_PORTS}
    volumes:
      - ./backend:${BACKEND_PATH}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: weather_frontend
    ports:
      - ${FRONTEND_PORTS}
    volumes:
      - ./frontend:${FRONTEND_PATH}
      - /app/frontend/node_modules
    stdin_open: true
    tty: true
    extra_hosts:
    - "host.docker.internal:host-gateway"

  redis:
    image: redis:7.4.1-alpine
    container_name: redis_server
    ports:
      - ${REDIS_PORTS}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

