services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: weather_backend
    ports:
      - ${BACKEND_PORTS}
    volumes:
      - ./backend:${BACKEND_PATH}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - redis
    networks:
      - backend_network
      - frontend_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: weather_frontend
    ports:
      - ${FRONTEND_PORTS}
    volumes:
      - ./frontend/src:/app/frontend/src
    stdin_open: true
    tty: true
    networks:
      - frontend_network

  redis:
    image: redis:7.4.1-alpine
    container_name: redis_server
    ports:
      - ${REDIS_PORTS}
    volumes:
      - ./redis_data:${REDIS_DATA_PATH}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge


  # db:
  #   image: postges:15
  #   container_name: weather_postgres
  #   enviroment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   ports:
  #     - ${DB_PORTS}
  #   volumes:
  #     - postgres_data:${POSTGRES_DATA_PATH}

volumes:
  postgres_data:
  redis_data: