services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: weather_backend
    ports:
      - ${BACKEND_PORTS}
    volumes:
      - ./backend:${BACKEND_PATH}
    environment:
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: weather_frontend
    ports:
      - ${FRONTEND_PORTS}
    volumes:
      - ./frontend:${FRONTEND_PATH}
      - /app/frontend/node_modules
    environment:
      VITE_GEOCODE_API_KEY: ${VITE_GEOCODE_API_KEY}

  redis:
    image: redis:7.4.1-alpine
    container_name: redis_server
    ports:
      - ${REDIS_PORTS}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

