name: CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "DB_PORTS=${{ secrets.DB_PORTS }}" >> .env
          echo "REDIS_PORTS=${{ secrets.REDIS_PORTS }}" >> .env
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env
          echo "REDIS_DATA_PATH=${{ vars.REDIS_DATA_PATH }}" >> .env
          echo "BACKEND_PORTS=${{ secrets.BACKEND_PORTS }}" >> .env
          echo "BACKEND_PATH=${{ vars.BACKEND_PATH }}" >> .env
          echo "FRONTEND_PORTS=${{ secrets.FRONTEND_PORTS }}" >> .env
          echo "FRONTEND_PATH=${{ vars.FRONTEND_PATH }}" >> .env
          echo "WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}" >> .env

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run Docker Compose
        run: docker compose up -d --build

      - name: Sleep for services to initialize
        run: sleep 10

      - name: Check frontend logs
        run: docker logs $(docker ps -q -f "name=weather_frontend")
        
      - name: Check backend logs
        run: docker logs $(docker ps -q -f "name=weather_backend")

      - name: Check redis logs
        run: docker logs $(docker ps -q -f "name=redis_server")

      - name: Verify Frontend
        run: |
          echo "Verifying Frontend (Vite)..."
          curl -X 'GET' --fail http://localhost:5173/
          docker logs $(docker ps -q -f "name=weather_frontend") 2>&1 | grep -i error && exit 1 || echo "No errors found in Frontend Vite: 5173."

      - name: Verify API responses and check logs
        run: |
          echo "Verifying Backend API..."
          curl -X 'GET' --fail http://localhost:8000/api/weather?city=Moscow
          curl -X 'GET' --fail http://localhost:8000/api/weather?city=Moscow
          curl -X 'GET' --fail http://localhost:8000/api/forecast?city=London
          curl -X 'GET' --fail http://localhost:8000/api/forecast?city=London
          docker logs $(docker ps -q -f "name=weather_backend") 2>&1 | grep -i error && exit 1 || echo "No errors found in Uvicorn logs."

      - name: Verify Redis
        run: |
          echo "Checking Redis connection..."
          docker exec $(docker ps -q -f "name=redis_server") redis-cli -a $REDIS_PASSWORD PING
          docker exec $(docker ps -q -f "name=redis_server") redis-cli -a $REDIS_PASSWORD KEYS *
          docker logs $(docker ps -q -f "name=redis_server") 2>&1 | grep -i error && exit 1 || echo "No errors found in Redis server."

