name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set environment variables
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          # POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          BACKEND_PORTS: ${{ secrets.BACKEND_PORTS }}
          # FRONTEND_PORTS: ${{ secrets.FRONTEND_PORTS }}
          # DB_PORTS: ${{ secrets.DB_PORTS }}
          # BACKEND_PATH: ${{ secrets.BACKEND_PATH }}
          # FRONTEND_PATH: ${{ secrets.FRONTEND_PATH }}
          # POSTGRES_DATA_PATH: ${{ secrets.POSTGRES_DATA_PATH }}
          # WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          # DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          echo "Environment variables loaded."

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run Docker Compose
        run: docker compose up -d --build

      - name: Stop and clean up
        run: docker compose down

      - name: Wait for the application to be ready
        run: |
          echo "Waiting for the app to be ready..."
          sleep 10
          curl --fail http://localhost:8000/